import { GarmentType } from './garmentData';

export interface ProductColor {
  name: string;
  hex: string;
  dark: boolean;
}

export interface ProductStyle {
  styleNumber: string;
  name: string;
  garmentType: GarmentType;
  colors: ProductColor[];
}

export interface Vendor {
  id: string;
  name: string;
  styles: ProductStyle[];
}

export const VENDOR_CATALOG: Vendor[] = [
  {
    id: 'ss-activewear',
    name: 'S&S Activewear',
    styles: [
      {
        styleNumber: 'G500',
        name: 'Gildan Heavy Cotton Tee',
        garmentType: 'tshirt',
        colors: [
          { name: 'White',              hex: '#FFFFFF', dark: false },
          { name: 'Black',              hex: '#1A1A1A', dark: true  },
          { name: 'Sport Grey',         hex: '#9E9E9E', dark: false },
          { name: 'Dark Heather',       hex: '#546E7A', dark: true  },
          { name: 'Ash',                hex: '#D0CEC8', dark: false },
          { name: 'Navy',               hex: '#1B2A4A', dark: true  },
          { name: 'Royal',              hex: '#1560BD', dark: true  },
          { name: 'Sapphire',           hex: '#0F52BA', dark: true  },
          { name: 'Carolina Blue',      hex: '#56A0D3', dark: false },
          { name: 'Sky',                hex: '#87CEEB', dark: false },
          { name: 'Red',                hex: '#C8102E', dark: true  },
          { name: 'Cherry Red',         hex: '#D2042D', dark: true  },
          { name: 'Cardinal',           hex: '#9B2335', dark: true  },
          { name: 'Antique Cherry Red', hex: '#A52020', dark: true  },
          { name: 'Maroon',             hex: '#800000', dark: true  },
          { name: 'Irish Green',        hex: '#009A44', dark: true  },
          { name: 'Forest Green',       hex: '#1B5E20', dark: true  },
          { name: 'Military Green',     hex: '#4A5240', dark: true  },
          { name: 'Gold',               hex: '#FFC107', dark: false },
          { name: 'Daisy',              hex: '#FFD700', dark: false },
          { name: 'Orange',             hex: '#FF6B35', dark: false },
          { name: 'Tangerine',          hex: '#F28500', dark: false },
          { name: 'Purple',             hex: '#6A1B9A', dark: true  },
          { name: 'Heliconia',          hex: '#DF3178', dark: true  },
          { name: 'Azalea',             hex: '#F18BA0', dark: false },
          { name: 'Sand',               hex: '#C2A882', dark: false },
          { name: 'Natural',            hex: '#F5F0E8', dark: false },
          { name: 'Charcoal',           hex: '#455A64', dark: true  },
          { name: 'Graphite Heather',   hex: '#616161', dark: true  },
        ],
      },
      {
        styleNumber: 'G185',
        name: 'Gildan Heavy Blend Hoodie',
        garmentType: 'hoodie',
        colors: [
          { name: 'White',          hex: '#FFFFFF', dark: false },
          { name: 'Black',          hex: '#1A1A1A', dark: true  },
          { name: 'Sport Grey',     hex: '#9E9E9E', dark: false },
          { name: 'Dark Heather',   hex: '#546E7A', dark: true  },
          { name: 'Navy',           hex: '#1B2A4A', dark: true  },
          { name: 'Royal',          hex: '#1560BD', dark: true  },
          { name: 'Carolina Blue',  hex: '#56A0D3', dark: false },
          { name: 'Red',            hex: '#C8102E', dark: true  },
          { name: 'Cardinal',       hex: '#9B2335', dark: true  },
          { name: 'Maroon',         hex: '#800000', dark: true  },
          { name: 'Forest Green',   hex: '#1B5E20', dark: true  },
          { name: 'Military Green', hex: '#4A5240', dark: true  },
          { name: 'Gold',           hex: '#FFC107', dark: false },
          { name: 'Orange',         hex: '#FF6B35', dark: false },
          { name: 'Purple',         hex: '#6A1B9A', dark: true  },
          { name: 'Heliconia',      hex: '#DF3178', dark: true  },
          { name: 'Sand',           hex: '#C2A882', dark: false },
          { name: 'Charcoal',       hex: '#455A64', dark: true  },
          { name: 'Ash',            hex: '#D0CEC8', dark: false },
        ],
      },
      {
        styleNumber: 'BC3001',
        name: 'Bella+Canvas Unisex Jersey Tee',
        garmentType: 'tshirt',
        colors: [
          { name: 'White',              hex: '#FFFFFF', dark: false },
          { name: 'Black',              hex: '#1A1A1A', dark: true  },
          { name: 'Dark Grey Heather',  hex: '#546E7A', dark: true  },
          { name: 'Athletic Heather',   hex: '#CFD8DC', dark: false },
          { name: 'Heather Navy',       hex: '#2D3F6B', dark: true  },
          { name: 'True Royal',         hex: '#1560BD', dark: true  },
          { name: 'Heather True Royal', hex: '#4B72C2', dark: true  },
          { name: 'Red',                hex: '#C8102E', dark: true  },
          { name: 'Heather Red',        hex: '#C94040', dark: true  },
          { name: 'Mauve',              hex: '#C8A2A2', dark: false },
          { name: 'Pink',               hex: '#F48FB1', dark: false },
          { name: 'Heather Maroon',     hex: '#8A3040', dark: true  },
          { name: 'Forest',             hex: '#1B5E20', dark: true  },
          { name: 'Heather Forest',     hex: '#3D7A45', dark: true  },
          { name: 'Military Green',     hex: '#4A5240', dark: true  },
          { name: 'Teal',               hex: '#00897B', dark: true  },
          { name: 'Storm',              hex: '#7B8D9E', dark: false },
          { name: 'Team Purple',        hex: '#6A1B9A', dark: true  },
          { name: 'Soft Cream',         hex: '#FFF8DC', dark: false },
          { name: 'Tan',                hex: '#D2B48C', dark: false },
          { name: 'Heather Peach',      hex: '#F5C5A3', dark: false },
          { name: 'Vintage White',      hex: '#FAF0E6', dark: false },
          { name: 'True Vintage Blue',  hex: '#5B7FA6', dark: true  },
          { name: 'Heather Sage',       hex: '#8FAF8F', dark: false },
          { name: 'Asphalt',            hex: '#37474F', dark: true  },
        ],
      },
      {
        styleNumber: 'BC3719',
        name: 'Bella+Canvas Sponge Fleece Hoodie',
        garmentType: 'hoodie',
        colors: [
          { name: 'White',             hex: '#FFFFFF', dark: false },
          { name: 'Black',             hex: '#1A1A1A', dark: true  },
          { name: 'Dark Grey Heather', hex: '#546E7A', dark: true  },
          { name: 'Athletic Heather',  hex: '#CFD8DC', dark: false },
          { name: 'Heather Navy',      hex: '#2D3F6B', dark: true  },
          { name: 'True Royal',        hex: '#1560BD', dark: true  },
          { name: 'Red',               hex: '#C8102E', dark: true  },
          { name: 'Heather Maroon',    hex: '#8A3040', dark: true  },
          { name: 'Military Green',    hex: '#4A5240', dark: true  },
          { name: 'Heather Forest',    hex: '#3D7A45', dark: true  },
          { name: 'Team Purple',       hex: '#6A1B9A', dark: true  },
          { name: 'Asphalt',           hex: '#37474F', dark: true  },
          { name: 'Heather Sage',      hex: '#8FAF8F', dark: false },
          { name: 'Tan',               hex: '#D2B48C', dark: false },
        ],
      },
      {
        styleNumber: 'NL3600',
        name: 'Next Level Premium Fitted Tee',
        garmentType: 'tshirt',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Heavy Metal',     hex: '#363636', dark: true  },
          { name: 'Dark Heather',    hex: '#546E7A', dark: true  },
          { name: 'Vintage Silver',  hex: '#B0B0B0', dark: false },
          { name: 'Light Blue',      hex: '#90CAF9', dark: false },
          { name: 'Royal',           hex: '#1560BD', dark: true  },
          { name: 'Indigo',          hex: '#3F51B5', dark: true  },
          { name: 'Midnight Navy',   hex: '#0D1B3E', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Cardinal',        hex: '#9B2335', dark: true  },
          { name: 'Vintage Red',     hex: '#B34040', dark: true  },
          { name: 'Kelly Green',     hex: '#4CBB17', dark: false },
          { name: 'Forest Green',    hex: '#1B5E20', dark: true  },
          { name: 'Vintage Gold',    hex: '#C8A400', dark: false },
          { name: 'Purple',          hex: '#6A1B9A', dark: true  },
          { name: 'Tahiti Blue',     hex: '#0288D1', dark: true  },
          { name: 'Vintage Pink',    hex: '#E8A0A0', dark: false },
          { name: 'Hot Pink',        hex: '#FF69B4', dark: false },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Vintage White',   hex: '#FAF0E6', dark: false },
        ],
      },
      {
        styleNumber: 'NL9300',
        name: 'Next Level Unisex Pullover Hoodie',
        garmentType: 'hoodie',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Dark Heather',    hex: '#546E7A', dark: true  },
          { name: 'Midnight Navy',   hex: '#0D1B3E', dark: true  },
          { name: 'Royal',           hex: '#1560BD', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Forest Green',    hex: '#1B5E20', dark: true  },
          { name: 'Purple',          hex: '#6A1B9A', dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Vintage Silver',  hex: '#B0B0B0', dark: false },
        ],
      },
    ],
  },

  {
    id: 'sanmar',
    name: 'SanMar',
    styles: [
      {
        styleNumber: 'PC54',
        name: 'Port & Company Core Cotton Tee',
        garmentType: 'tshirt',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Athletic Heather',hex: '#CFD8DC', dark: false },
          { name: 'Dark Heather Grey',hex: '#546E7A',dark: true  },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Royal',           hex: '#1560BD', dark: true  },
          { name: 'Light Blue',      hex: '#90CAF9', dark: false },
          { name: 'Carolina Blue',   hex: '#56A0D3', dark: false },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Cardinal',        hex: '#9B2335', dark: true  },
          { name: 'Maroon',          hex: '#800000', dark: true  },
          { name: 'Kelly',           hex: '#4CBB17', dark: false },
          { name: 'Forest Green',    hex: '#1B5E20', dark: true  },
          { name: 'Gold',            hex: '#FFC107', dark: false },
          { name: 'Yellow',          hex: '#FFD700', dark: false },
          { name: 'Orange',          hex: '#FF6B35', dark: false },
          { name: 'Purple',          hex: '#6A1B9A', dark: true  },
          { name: 'Sangria',         hex: '#92000A', dark: true  },
          { name: 'Safety Green',    hex: '#AAFF00', dark: false },
          { name: 'Safety Orange',   hex: '#FF6600', dark: false },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Denim',           hex: '#1560BD', dark: true  },
          { name: 'Tan',             hex: '#D2B48C', dark: false },
          { name: 'Natural',         hex: '#F5F0E8', dark: false },
          { name: 'Ash',             hex: '#D0CEC8', dark: false },
        ],
      },
      {
        styleNumber: 'PC90H',
        name: 'Port & Company Pullover Hoodie',
        garmentType: 'hoodie',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Athletic Heather',hex: '#CFD8DC', dark: false },
          { name: 'Dark Heather Grey',hex: '#546E7A',dark: true  },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Royal',           hex: '#1560BD', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Cardinal',        hex: '#9B2335', dark: true  },
          { name: 'Maroon',          hex: '#800000', dark: true  },
          { name: 'Forest Green',    hex: '#1B5E20', dark: true  },
          { name: 'Gold',            hex: '#FFC107', dark: false },
          { name: 'Purple',          hex: '#6A1B9A', dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Ash',             hex: '#D0CEC8', dark: false },
          { name: 'Sangria',         hex: '#92000A', dark: true  },
        ],
      },
      {
        styleNumber: 'DT6000',
        name: 'District Very Important Tee',
        garmentType: 'tshirt',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Heathered Charcoal',hex: '#546E7A',dark: true },
          { name: 'Heathered Navy',  hex: '#2D3F6B', dark: true  },
          { name: 'True Royal',      hex: '#1560BD', dark: true  },
          { name: 'Red Pepper',      hex: '#C8102E', dark: true  },
          { name: 'Pomegranate',     hex: '#9B2335', dark: true  },
          { name: 'Heathered Teal',  hex: '#2E8B8B', dark: true  },
          { name: 'True Teal',       hex: '#008080', dark: true  },
          { name: 'Forest Green',    hex: '#1B5E20', dark: true  },
          { name: 'Light Pink',      hex: '#F48FB1', dark: false },
          { name: 'Soft Rose',       hex: '#E8A0A0', dark: false },
          { name: 'Sun Drenched',    hex: '#D4A056', dark: false },
          { name: 'New Navy',        hex: '#0D1B3E', dark: true  },
          { name: 'Heathered Grape', hex: '#7B4F8A', dark: true  },
          { name: 'Heathered Copper',hex: '#A0522D', dark: true  },
          { name: 'Cloud',           hex: '#E8E8E8', dark: false },
          { name: 'Washed Coal',     hex: '#5A5A5A', dark: true  },
        ],
      },
      {
        styleNumber: 'DT1100',
        name: 'District Perfect Tri Tee',
        garmentType: 'tshirt',
        colors: [
          { name: 'Tri White',       hex: '#F5F5F0', dark: false },
          { name: 'Tri Black',       hex: '#2C2C2C', dark: true  },
          { name: 'Tri Charcoal',    hex: '#5A5A5A', dark: true  },
          { name: 'Tri Dark Navy',   hex: '#1A2A4A', dark: true  },
          { name: 'Tri Royal',       hex: '#2A6AB5', dark: true  },
          { name: 'Tri Red',         hex: '#B52020', dark: true  },
          { name: 'Tri Maroon',      hex: '#7A2030', dark: true  },
          { name: 'Tri Purple',      hex: '#5A1A7A', dark: true  },
          { name: 'Tri Green',       hex: '#2A6A2A', dark: true  },
          { name: 'Tri Turquoise',   hex: '#1A8080', dark: true  },
          { name: 'Tri Gold',        hex: '#C8A000', dark: false },
        ],
      },
      {
        styleNumber: 'PC78H',
        name: 'Port & Company Core Fleece Pullover Hoodie',
        garmentType: 'hoodie',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Ash',             hex: '#D0CEC8', dark: false },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Royal',           hex: '#1560BD', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Cardinal',        hex: '#9B2335', dark: true  },
          { name: 'Gold',            hex: '#FFC107', dark: false },
          { name: 'Purple',          hex: '#6A1B9A', dark: true  },
          { name: 'Dark Heather Grey',hex: '#546E7A',dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Safety Green',    hex: '#AAFF00', dark: false },
        ],
      },
    ],
  },

  {
    id: 'itc',
    name: 'Independent Trading Co.',
    styles: [
      {
        styleNumber: 'IND500',
        name: 'Heavyweight Short Sleeve Tee',
        garmentType: 'tshirt',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Gunmetal',        hex: '#2C3539', dark: true  },
          { name: 'Slate',           hex: '#7B8D9E', dark: false },
          { name: 'Light Grey',      hex: '#D3D3D3', dark: false },
          { name: 'True Navy',       hex: '#1B2A4A', dark: true  },
          { name: 'Cobalt',          hex: '#0047AB', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Crimson',         hex: '#DC143C', dark: true  },
          { name: 'Maroon',          hex: '#800000', dark: true  },
          { name: 'Cardinal',        hex: '#9B2335', dark: true  },
          { name: 'Hunter Green',    hex: '#355E3B', dark: true  },
          { name: 'Army',            hex: '#4A5240', dark: true  },
          { name: 'Bone',            hex: '#E8E4DA', dark: false },
          { name: 'Sand',            hex: '#C2B280', dark: false },
          { name: 'Gold',            hex: '#FFD700', dark: false },
          { name: 'Purple',          hex: '#6A1B9A', dark: true  },
        ],
      },
      {
        styleNumber: 'IND4000',
        name: 'Heavyweight Hooded Pullover',
        garmentType: 'hoodie',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Gunmetal',        hex: '#2C3539', dark: true  },
          { name: 'Slate',           hex: '#7B8D9E', dark: false },
          { name: 'Light Grey',      hex: '#D3D3D3', dark: false },
          { name: 'True Navy',       hex: '#1B2A4A', dark: true  },
          { name: 'Cobalt',          hex: '#0047AB', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Maroon',          hex: '#800000', dark: true  },
          { name: 'Cardinal',        hex: '#9B2335', dark: true  },
          { name: 'Hunter Green',    hex: '#355E3B', dark: true  },
          { name: 'Army',            hex: '#4A5240', dark: true  },
          { name: 'Bone',            hex: '#E8E4DA', dark: false },
          { name: 'Sand',            hex: '#C2B280', dark: false },
          { name: 'Gold',            hex: '#FFD700', dark: false },
          { name: 'Purple',          hex: '#6A1B9A', dark: true  },
        ],
      },
      {
        styleNumber: 'SS150',
        name: 'Midweight Short Sleeve Tee',
        garmentType: 'tshirt',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Slate',           hex: '#7B8D9E', dark: false },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Storm',           hex: '#5A7080', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Forest',          hex: '#2D5A27', dark: true  },
          { name: 'Army',            hex: '#4A5240', dark: true  },
          { name: 'Sand',            hex: '#C2B280', dark: false },
          { name: 'Bone',            hex: '#E8E4DA', dark: false },
        ],
      },
      {
        styleNumber: 'IND5000P',
        name: 'Heavyweight Crewneck Sweatshirt',
        garmentType: 'crewneck',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Gunmetal',        hex: '#2C3539', dark: true  },
          { name: 'Slate',           hex: '#7B8D9E', dark: false },
          { name: 'True Navy',       hex: '#1B2A4A', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Maroon',          hex: '#800000', dark: true  },
          { name: 'Hunter Green',    hex: '#355E3B', dark: true  },
          { name: 'Army',            hex: '#4A5240', dark: true  },
          { name: 'Bone',            hex: '#E8E4DA', dark: false },
          { name: 'Sand',            hex: '#C2B280', dark: false },
          { name: 'Purple',          hex: '#6A1B9A', dark: true  },
        ],
      },
      {
        styleNumber: 'PRM4500',
        name: 'Midweight Fleece Pullover Hoodie',
        garmentType: 'hoodie',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Slate',           hex: '#7B8D9E', dark: false },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Storm',           hex: '#5A7080', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Forest',          hex: '#2D5A27', dark: true  },
          { name: 'Army',            hex: '#4A5240', dark: true  },
          { name: 'Bone',            hex: '#E8E4DA', dark: false },
        ],
      },
    ],
  },

  {
    id: 'shaka-wear',
    name: 'Shaka Wear',
    styles: [
      {
        styleNumber: 'SHGW',
        name: 'Garment Washed Heavyweight Tee',
        garmentType: 'tshirt',
        colors: [
          { name: 'White',           hex: '#F5F0E8', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Slate',           hex: '#6B7D8A', dark: true  },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Royal',           hex: '#1560BD', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Maroon',          hex: '#800000', dark: true  },
          { name: 'Forest',          hex: '#2D4A2D', dark: true  },
          { name: 'Army',            hex: '#4A5240', dark: true  },
          { name: 'Sand',            hex: '#C4A882', dark: false },
          { name: 'Bone',            hex: '#E8E0CE', dark: false },
          { name: 'Purple',          hex: '#6A1B9A', dark: true  },
          { name: 'Pink',            hex: '#E8A0B0', dark: false },
          { name: 'Sage',            hex: '#8FAF8F', dark: false },
          { name: 'Dusty Blue',      hex: '#7B9EB5', dark: false },
          { name: 'Vintage Brown',   hex: '#8B6355', dark: true  },
          { name: 'Rust',            hex: '#B7410E', dark: true  },
        ],
      },
      {
        styleNumber: 'SHSS',
        name: 'Super Max Heavyweight Tee',
        garmentType: 'tshirt',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Dark Heather',    hex: '#546E7A', dark: true  },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Royal',           hex: '#1560BD', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Cardinal',        hex: '#9B2335', dark: true  },
          { name: 'Maroon',          hex: '#800000', dark: true  },
          { name: 'Forest Green',    hex: '#1B5E20', dark: true  },
          { name: 'Military Green',  hex: '#4A5240', dark: true  },
          { name: 'Gold',            hex: '#FFC107', dark: false },
          { name: 'Purple',          hex: '#6A1B9A', dark: true  },
          { name: 'Ash',             hex: '#D0CEC8', dark: false },
          { name: 'Sand',            hex: '#C2B280', dark: false },
        ],
      },
      {
        styleNumber: 'SHGWH',
        name: 'Garment Washed Heavyweight Hoodie',
        garmentType: 'hoodie',
        colors: [
          { name: 'White',           hex: '#F5F0E8', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Slate',           hex: '#6B7D8A', dark: true  },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Maroon',          hex: '#800000', dark: true  },
          { name: 'Forest',          hex: '#2D4A2D', dark: true  },
          { name: 'Army',            hex: '#4A5240', dark: true  },
          { name: 'Sand',            hex: '#C4A882', dark: false },
          { name: 'Bone',            hex: '#E8E0CE', dark: false },
          { name: 'Sage',            hex: '#8FAF8F', dark: false },
          { name: 'Dusty Blue',      hex: '#7B9EB5', dark: false },
          { name: 'Rust',            hex: '#B7410E', dark: true  },
          { name: 'Purple',          hex: '#6A1B9A', dark: true  },
        ],
      },
      {
        styleNumber: 'SHGWC',
        name: 'Garment Washed Crewneck Sweatshirt',
        garmentType: 'crewneck',
        colors: [
          { name: 'White',           hex: '#F5F0E8', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Slate',           hex: '#6B7D8A', dark: true  },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Maroon',          hex: '#800000', dark: true  },
          { name: 'Army',            hex: '#4A5240', dark: true  },
          { name: 'Sand',            hex: '#C4A882', dark: false },
          { name: 'Bone',            hex: '#E8E0CE', dark: false },
          { name: 'Sage',            hex: '#8FAF8F', dark: false },
          { name: 'Rust',            hex: '#B7410E', dark: true  },
        ],
      },
    ],
  },

  {
    id: 'la-apparel',
    name: 'LA Apparel',
    styles: [
      {
        styleNumber: '1801GD',
        name: 'Garment Dye T-Shirt',
        garmentType: 'tshirt',
        colors: [
          { name: 'White',           hex: '#FEFEFE', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Slate',           hex: '#7B8D9E', dark: false },
          { name: 'Dusty Blue',      hex: '#7B9EB5', dark: false },
          { name: 'Stone Blue',      hex: '#5B7FA6', dark: true  },
          { name: 'Pine',            hex: '#2D4A2D', dark: true  },
          { name: 'Sage',            hex: '#8FAF8F', dark: false },
          { name: 'Army',            hex: '#4A5240', dark: true  },
          { name: 'Plum',            hex: '#5E2750', dark: true  },
          { name: 'Mauve',           hex: '#C8A2A2', dark: false },
          { name: 'Poppy',           hex: '#E8341C', dark: true  },
          { name: 'Clay',            hex: '#C07850', dark: true  },
          { name: 'Rust',            hex: '#B7410E', dark: true  },
          { name: 'Natural',         hex: '#F5F0E8', dark: false },
          { name: 'Butter',          hex: '#FFF3A8', dark: false },
          { name: 'Peach',           hex: '#FFCBA4', dark: false },
          { name: 'Lavender',        hex: '#D8B4E2', dark: false },
          { name: 'Pink',            hex: '#F48FB1', dark: false },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Gold',            hex: '#C8A000', dark: false },
        ],
      },
      {
        styleNumber: '8890W',
        name: 'Heavy Cotton T-Shirt',
        garmentType: 'tshirt',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Heather Grey',    hex: '#B0BEC5', dark: false },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Royal',           hex: '#1560BD', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Forest Green',    hex: '#1B5E20', dark: true  },
          { name: 'Gold',            hex: '#FFC107', dark: false },
          { name: 'Natural',         hex: '#F5F0E8', dark: false },
          { name: 'Bone',            hex: '#E8E0CE', dark: false },
          { name: 'Lavender',        hex: '#D8B4E2', dark: false },
          { name: 'Pink',            hex: '#F48FB1', dark: false },
          { name: 'Maroon',          hex: '#800000', dark: true  },
        ],
      },
      {
        styleNumber: 'F297',
        name: 'Heavy Fleece Pullover Hoodie',
        garmentType: 'hoodie',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Dusty Blue',      hex: '#7B9EB5', dark: false },
          { name: 'Pine',            hex: '#2D4A2D', dark: true  },
          { name: 'Sage',            hex: '#8FAF8F', dark: false },
          { name: 'Army',            hex: '#4A5240', dark: true  },
          { name: 'Plum',            hex: '#5E2750', dark: true  },
          { name: 'Red',             hex: '#C8102E', dark: true  },
          { name: 'Natural',         hex: '#F5F0E8', dark: false },
          { name: 'Rust',            hex: '#B7410E', dark: true  },
          { name: 'Mauve',           hex: '#C8A2A2', dark: false },
        ],
      },
      {
        styleNumber: 'CO93',
        name: 'Flex Fleece Crewneck Sweatshirt',
        garmentType: 'crewneck',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Dusty Blue',      hex: '#7B9EB5', dark: false },
          { name: 'Pine',            hex: '#2D4A2D', dark: true  },
          { name: 'Sage',            hex: '#8FAF8F', dark: false },
          { name: 'Plum',            hex: '#5E2750', dark: true  },
          { name: 'Mauve',           hex: '#C8A2A2', dark: false },
          { name: 'Natural',         hex: '#F5F0E8', dark: false },
          { name: 'Rust',            hex: '#B7410E', dark: true  },
        ],
      },
      {
        styleNumber: '5314W',
        name: 'Flex Fleece Long Sleeve T-Shirt',
        garmentType: 'longsleeve',
        colors: [
          { name: 'White',           hex: '#FFFFFF', dark: false },
          { name: 'Black',           hex: '#1A1A1A', dark: true  },
          { name: 'Charcoal',        hex: '#455A64', dark: true  },
          { name: 'Navy',            hex: '#1B2A4A', dark: true  },
          { name: 'Dusty Blue',      hex: '#7B9EB5', dark: false },
          { name: 'Sage',            hex: '#8FAF8F', dark: false },
          { name: 'Natural',         hex: '#F5F0E8', dark: false },
          { name: 'Mauve',           hex: '#C8A2A2', dark: false },
        ],
      },
    ],
  },
];
